[package]
authors = ["domechn"]
description = "A Tauri App"
edition = "2021"
license = ""
name = "track3"
repository = ""
rust-version = "1.57"
version = "0.4.19"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.5", features = [] }

[dependencies]
binance-rs-async = {version = "1.3.1", features = ["wallet_api", "futures_api", "savings_api"] }
coingecko = {git = "https://github.com/domechn/coingecko-rs.git", rev = "41e819e"}
lazy_static = "^1.4"
magic-crypt = "3.1.12"
okex = {git = "https://github.com/domechn/okex-rs.git", rev = "7c101a9"}
rand = "^0.3"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = {version = "0.6", features = ["runtime-tokio-rustls", "sqlite"] }
tauri = {version = "1.5", features = [ "shell-open", "app-all", "dialog-open", "dialog-save", "fs-exists", "fs-read-file", "fs-write-file", "http-all", "path-all", "process-relaunch", "protocol-asset", "updater"] }
tokio = {version = "1", features = ["sync"] }
uuid = "1.3.3"
tauri-plugin-aptabase = "0.3"
reqwest = "0.11.22"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[dependencies.tauri-plugin-sql]
branch = "v1"
features = ["sqlite"] # or "postgres", or "mysql"
git = "https://github.com/tauri-apps/plugins-workspace"
